### ISSUE TITLE
Not working when using without Spring Security

### ISSUE THREAD

**Issue by anumontu** [harshilsharma63/controller-logger#20]
java.lang.NullPointerException: null
        at io.github.logger.controller.utils.RequestUtil.getRequestUserName(RequestUtil.java:37) ~[controller-logger-1.2.3.jar:na]
        at io.github.logger.controller.utils.RequestUtil.getRequestContext(RequestUtil.java:22) ~[controller-logger-1.2.3.jar:na]

**Comment by armdev** [comment]
+
